### ISSUE TITLE
toSpark() must be called with Converter instance as first argument 

### ISSUE THREAD

**Issue by fissehab** [databricks/spark-sklearn#108]
I want to convert a sklearn logistic regression model to Spark but it is not working for me:

`from spark_sklearn import Converter
logreg_spark_ml = Converter.toSpark(logreg_cv)
`

> TypeError: unbound method toSpark() must be called with Converter instance as first argument (got GridSearchCV instance instead)

**Comment by srowen** [comment]
You need an instance of Converter. See how it's used in the tests, for example: 
https://github.com/databricks/spark-sklearn/blob/705401005de4c951604645e737ea303a1788709f/python/spark_sklearn/converter_test.py#L19

**Comment by fissehab** [comment]
I have seen the tests but I do not get it how to create an instance of Converter.

**Comment by srowen** [comment]
(See the very line I quoted! you need to pass it an instance of SparkContext)

**Comment by fissehab** [comment]
so if I have a logistic regression object called log_reg and the instance of SparkContext is sc, how do I do it?
