### ISSUE TITLE
spark-sklearn on windows- not working on local

### ISSUE THREAD

**Issue by mohkar123** [databricks/spark-sklearn#110]
am trying to execute this code from the spark-sklearn API documentation. I'm running on Windows 7 and on the latest spark-sklearn version. I'm executing inside the pyspark shell. Running spark version 2.3.2 (tried 2.4.0, same error)
```
from sklearn.linear_model import LinearRegression
from sklearn.cluster import KMeans
from pyspark.ml.linalg import Vectors, Matrices, MatrixUDT
from pyspark.sql.functions import udf
from pyspark.sql import SparkSession
from spark_sklearn.util import createLocalSparkSession
from spark_sklearn.keyed_models import KeyedEstimator
spark = createLocalSparkSession()
df = spark.createDataFrame([(user,
                             Vectors.dense([i, i ** 2, i ** 3]),
                             0.0 + user + i + 2 * i ** 2 + 3 * i ** 3)
                            for user in range(3) for i in range(5)])
df = df.toDF("key", "features", "y")
df.where("5 < y and y < 10").sort("key", "y").show()

km = KeyedEstimator(sklearnEstimator=LinearRegression(), yCol="y").fit(df)
def printFloat(x):
    rounded = round(x, 2)
    return "{:.2f}".format(0 if rounded == 0 else rounded)

def printModel(model):
    coef = "[" + ", ".join(map(printFloat, model.coef_)) + "]"
    intercept = printFloat(model.intercept_)
    return "intercept: {} coef: {}".format(intercept, coef)

km.keyedModels.columns

printedModels = udf(printModel)("estimator").alias("linear fit")
km.keyedModels.select("key", printedModels).sort("key").show(truncate=False)`
```

On running this I get the following error on the show at `km.keyedModels.select("key", printedModels).sort("key").show(truncate=False)`

![image](https://user-images.githubusercontent.com/10978313/56326492-dec61900-613b-11e9-93cc-3f041ec6d70c.png)
 I cannot seem to find any solution online. Since the show before this is working, clearly my spark seems to be working.

**Comment by srowen** [comment]
This doesn't look like an issue with this library. You are hitting some kind of network error. I don't know why that is, but it's possible you aren't successfully starting a cluster, you have a VPN-related issue, Python version mismatch, etc.

**Comment by mohkar123** [comment]
I am running this on my local system. So it's doing multithreading. So
cluster and or VPN related issues are not possible. I'm using Python
Verizon 3.6.8. should I be using a lower version?

**Comment by srowen** [comment]
I don't know, but this isn't an error related to this library. Even when running locally, you'd be surprised what can go wrong connecting to localhost, esp. on Windows. I'd check whether you can run any pyspark command successfully. I'd use Spark 2.4.1 to be fully up to date, but don't think that is the problem.

**Comment by mohkar123** [comment]
I can run any pyspark command perfectly. The spark command above this line
ran perfectly.

**Comment by srowen** [comment]
My only other idea is that your data set is very large and it is not able to succeed in broadcasting it.

**Comment by mohkar123** [comment]
Hmm. If you look at my code, I'm running the example from spark-sklearn
API. It's an example code which does not load any dataset.

**Comment by srowen** [comment]
I get this error when running your code on my Mac:
```
py4j.protocol.Py4JJavaError: An error occurred while calling o150.showString.
: org.apache.spark.SparkException: Job aborted due to stage failure: Task 7 in stage 2.0 failed 1 times, most recent failure: Lost task 7.0 in stage 2.0 (TID 22, localhost, executor driver): org.apache.spark.SparkException: Python worker exited unexpectedly (crashed)
	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator$$anonfun$3.applyOrElse(PythonRunner.scala:486)
	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator$$anonfun$3.applyOrElse(PythonRunner.scala:475)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at org.apache.spark.sql.execution.python.PythonUDFRunner$$anon$1.read(PythonUDFRunner.scala:86)
	at org.apache.spark.sql.execution.python.PythonUDFRunner$$anon$1.read(PythonUDFRunner.scala:64)
	at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:406)
	at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
	at scala.collection.Iterator$$anon$12.hasNext(Iterator.scala:440)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:409)
	at org.apache.spark.sql.catalyst.expressions.GeneratedClass$GeneratedIteratorForCodegenStage2.processNext(Unknown Source)
	at org.apache.spark.sql.execution.BufferedRowIterator.hasNext(BufferedRowIterator.java:43)
	at org.apache.spark.sql.execution.WholeStageCodegenExec$$anonfun$13$$anon$1.hasNext(WholeStageCodegenExec.scala:636)
...
Caused by: java.io.EOFException
	at java.io.DataInputStream.readInt(DataInputStream.java:392)
	at org.apache.spark.sql.execution.python.PythonUDFRunner$$anon$1.read(PythonUDFRunner.scala:71)
	... 25 more
```

```
objc[75794]: +[__NSPlaceholderDictionary initialize] may have been in progress in another thread when fork() was called.
objc[75794]: +[__NSPlaceholderDictionary initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```

Python crashed, which is weird. It's still not an issue with this library, but that is unexpected and weird indeed. I haven't seen this crash in Spark either.

I don't know if it's actually the same problem you're seeing but it sure would be a coincidence if not.

The only issue I've seen recently that might be relevant is https://github.com/apache/spark/pull/24070 but I don't know if that's the problem.

The example at https://github.com/databricks/spark-sklearn and all the tests in this project work

I'll try to reproduce on Linux too for our info, but, this would at best be a bug to report vs Spark.

**Comment by mohkar123** [comment]
This is the error I was getting. I don't know which line it crashed for
you, but because it crashed at the fit, I was assuming it was a library
issue. Maybe it's not. But I don't know what the issue is either.
