### ISSUE TITLE
Training large number of models

### ISSUE THREAD

**Issue by danielnee** [databricks/spark-sklearn#12]
Hi,

This looks fantastic and looks to almost solve one of my problems.

Essentially I have a model to predict the amount of sales of a particular product for each day given various features (historical sales volumes, type of store, day of week, time of year, etc.). The training set fits easily in memory,

I want to train this model for 1000's of different products (we need a model per product)

The features and model used are the same. The exact values of the features will change per product.

In pseudo code this looks like:

```
for (product in products) { # We can parallelise this loop on a single machine, but could we parallelise over spark?

   # Extract train dataset from hive over ODBC
   # Train model
   # Output predictions
}
```

Any thoughts if spark-sklearn could be used to support this?

**Comment by thunterdb** [comment]
Hello Daniel, it looks like you want to train independent models in parallel. In this case, you may be better off using directly Spark (or Joblib if you want to run a single computer), I believe. They both fit exactly the description of your problem.

**Comment by danielnee** [comment]
Hi Timothy,

Thanks for your response. Yes, I essentially want to train many independent models in parallel.

So say I want to train 1000 independent models:
- I can use joblib on a single machine
- I could launch 1000 (fairly small) spark jobs at the same time.

The latter feels a bit clunky, essentially I am looking for a better way to do the latter

**Comment by thunterdb** [comment]
@danielnee I think your use case fits more directly for spark, so I am going to close this request for now. Feel free however to submit a patch if you end up writing some reusable wrappers for this task.
