### ISSUE TITLE
Randomized Search

### ISSUE THREAD

**Issue by sixers** [databricks/spark-sklearn#15]
Hey!

Would it be possible to implement a distributed version of http://scikit-learn.org/stable/modules/generated/sklearn.grid_search.RandomizedSearchCV.html ?

**Comment by thunterdb** [comment]
Hello Mateusz, yes, the randomized search is planned for a future release.

**Comment by gnsiva** [comment]
Added a pull request for this:
https://github.com/databricks/spark-sklearn/pull/48

**Comment by munro** [comment]
Woops just realized I duplicated this with #77 #78.  What do we have to do to get this feature in?! 😄

**Comment by srowen** [comment]
@ThunderShiviah you mentioned you wanted to update and merge a random CV pull request; looks like we have several to choose from! the tests are working again and I've patched up several other errors. You're clear to go ahead

**Comment by thunterdb** [comment]
Looking forward to this feature

**Comment by srowen** [comment]
See #100
