### ISSUE TITLE
CSR Matrix Support for Spark 2.0

### ISSUE THREAD

**Issue by vlad17** [databricks/spark-sklearn#24]
There's no support for CSR matrices in Spark 2.0.

To replicate, run `python/run-tests.sh --nologcapture spark_sklearn.converter_test`

**Comment by fabboe** [comment]
Could you test on https://github.com/databricks/spark-sklearn/releases/tag/release-0.2.0?

**Comment by vlad17** [comment]
Yes; this test only passes because I put in a skip decoration.

**Comment by srowen** [comment]
Looks like it was resolved, as this PR that removes the skipping passes: https://github.com/databricks/spark-sklearn/pull/94
