### ISSUE TITLE
GridSearchCV documentation generation warnings

### ISSUE THREAD

**Issue by vlad17** [databricks/spark-sklearn#37]
Here's the warnings from a generation run, which need to be fixed: https://gist.github.com/vlad17/5ed3d53c28474e67ccafc5e4d48a245f

**Comment by srowen** [comment]
Yep, I'll fix this. The problem is the docs are just copied from scikit and not all the references are correct. Those attributes don't exist in this derived class.

**Comment by srowen** [comment]
This should be resolved by https://github.com/databricks/spark-sklearn/pull/95 _except_ for the warnings about missing attributes. That's a larger issue I'm going to track separately.
