### ISSUE TITLE
gridsearch with StratifiedShuffleSplit error

### ISSUE THREAD

**Issue by ginberg** [databricks/spark-sklearn#45]
Hi, I am getting this error when running the code below
'StratifiedShuffleSplit' object is not iterable

from sklearn import svm, grid_search, datasets
from sklearn.model_selection import StratifiedShuffleSplit
from spark_sklearn import GridSearchCV
iris = datasets.load_iris()

parameters = {'kernel':('linear', 'rbf'), 'C':[1, 10]}

svr = svm.SVC()
sss = StratifiedShuffleSplit(n_splits=10, test_size=0.5)
clf = GridSearchCV(sc, svr, parameters, cv=sss)
clf.fit(iris.data, iris.target)

**Comment by seralouk** [comment]
Same question. Any solution so far?

**Comment by ginberg** [comment]
https://github.com/ginberg/spark-sklearn

**Comment by seralouk** [comment]
Thank you. 
Also, another solution is the following:

replace 
from sklearn import grid_search

with
**from sklearn.model_selection import GridSearchCV**

**Comment by srowen** [comment]
After a looong delay, cleaning up old issues here. Does this still occur, and what line in spark-sklearn raises the error? It generally just passes through the cv object to scikit, and uses it in the same way as the implementation here mostly copy-pastes the scikit one.

@ginberg what was, roughly, your solution? is it a simple fix?

@seralouk I don't quite get your workaround; the example doesn't use GridSearchCV from _scikit_. Could you elaborate?
