### ISSUE TITLE
Question about further support

### ISSUE THREAD

**Issue by praveend** [databricks/spark-sklearn#47]
Hi,

I am looking for road map information on this project. In specific I am looking for, if there is any work going on/plans for support of using the model generated from scikit in Spark pipelineModel and also any plans on support of other ML Algorithms like Decision Tress, K-means etc.

Could anyone shed some light on this.

Thanks
Praveen

**Comment by srowen** [comment]
There's no particular roadmap for future development right now. Right now, mostly looking at getting the project updated and merging some long-standing feature requests. So take a look at the open issues for a guide about what people want to add.
