### ISSUE TITLE
AttributeError: 'function' object has no attribute '_input_kwargs'

### ISSUE THREAD

**Issue by sounakban** [databricks/spark-sklearn#59]
I am using python 2.7, spark-2.2.0 with hadoop2.7 and sklearn 0.19.
I get the following error:
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    km = KeyedEstimator(sklearnEstimator=LinearRegression(), yCol="y").fit(df)
  File "C:\spark-2.2.0-bin-hadoop2.7\python\pyspark\\_\_init\_\_.py", line 104, in wrapper
    return func(self, **kwargs)
  File "C:\Python27\lib\site-packages\spark_sklearn\keyed_models.py", line 323, in \_\_init\_\_
    kwargs = KeyedEstimator._inferredParams(sklearnEstimator, self.\_\_init\_\_._input_kwargs)
AttributeError: 'function' object has no attribute '_input_kwargs'

when I try to run the code:
km = KeyedEstimator(sklearnEstimator=LinearRegression(), yCol="y").fit(df)
From the origian example code available in the welcome page.
I also tried the Kmeans clustering, but it caused the same error.

I downloaded the source code and checked line 323 in keyed_models.py, which was:
kwargs = KeyedEstimator._inferredParams(sklearnEstimator, self._input_kwargs)
Please correct me if I'm wrong but the two, do not seem to match

**Comment by srowen** [comment]
It looks like this was a compatibility issue with Spark 2.1, and was resolved in https://github.com/databricks/spark-sklearn/commit/66363f054c831e5def8411d2021060fae3ab4a70#diff-66bfa1405c485d5a76e4b7436683ab04R323
