### ISSUE TITLE
Implement parallelized RandomizedSearchCV

### ISSUE THREAD

**Issue by munro** [databricks/spark-sklearn#77]
This is a very useful tool in sklearn for me, I could make my case but there's a lot of places online that explains it much better than I can.

https://medium.com/rants-on-machine-learning/smarter-parameter-sweeps-or-why-grid-search-is-plain-stupid-c17d97a0e881

https://stats.stackexchange.com/questions/160479/practical-hyperparameter-optimization-random-vs-grid-search

http://scikit-learn.org/stable/auto_examples/model_selection/plot_randomized_search.html

**Comment by srowen** [comment]
Let me just close this as a duplicate to funnel the conversation into one place: https://github.com/databricks/spark-sklearn/issues/15
