### ISSUE TITLE
Spark 2.3 compatible?

### ISSUE THREAD

**Issue by Tagar** [databricks/spark-sklearn#82]
Seems to be such a great idea / use case to run `sklearn` distributely through Spark!
Haven't seen `databricks/spark-sklearn` updates for almost a year.. is this an active project? 
Is this known to work with Spark 2.3? 
Thank you.

**Comment by nEosAg007** [comment]
I echo @Tagar's doubt

**Comment by srowen** [comment]
It does work with Spark 2.3. I just fixed the build and added a Travis profile for it.
