### ISSUE TITLE
"TypeError: Can't instantiate abstract class GridSearchCV with abstract methods _run_search"

### ISSUE THREAD

**Issue by cmglaze** [databricks/spark-sklearn#86]
Getting this error after a very basic call to GridSearchCV on Databricks:
 
![capture](https://user-images.githubusercontent.com/43760238/46307495-121cce00-c585-11e8-90ed-443baddd658e.PNG)

**Comment by srowen** [comment]
Yes, it doesn't work with 0.20 right now. This is essentially what https://github.com/databricks/spark-sklearn/issues/53 is about
