### ISSUE TITLE
ImportError: No module named

### ISSUE THREAD

**Issue by PoeteMaudit** [databricks/spark-sklearn#87]
Please have a look at my post on StackOverflow: https://stackoverflow.com/questions/52985968/gridsearchcv-on-spark-cluster-importerror-no-module-named.

I am not entirely sure that the error which I am getting has to do directly with `spark-sklearn` but this is a nice opportunity to clarify this.

**Comment by srowen** [comment]
I think this one is correctly answered on SO.
